# Generated by Django 4.0.3 on 2022-08-06 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_rating_movie'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movieshots',
            options={'verbose_name': 'Кадр из фильма', 'verbose_name_plural': 'Кадры из фильмов'},
        ),
        migrations.AlterModelOptions(
            name='reviews',
            options={'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
    ]
